### ISSUE TITLE
Fitzpatrick-17K file list?

### ISSUE THREAD

**Issue by divyashan** [Digital-Dermatology/SelfClean-Revised-Benchmarks#2]
Hello-

I was wondering if the revised file list for Fitzpatrick-17K is available somewhere? I'd love to train + evaluate some models on the cleaned version of the dataset.

And thank you for this work- I appreciate it!
Divya

**Comment by FabianGroeger96** [comment]
Dear Divya

Thanks a lot for reaching out to us!
Unfortunately for Fitzpatrick17k we have only performed cleaning using the automatic mode of SelfClean.
As we are not recommending this for high-stakes domains such as the medical one we solely showcase a significant performance difference when using the cleaned version and refrain from open-sourcing this revised list as the resulting dataset might still contain inaccuracies.

We are however currently working with the creators of Fitzpatrick17k on a revised version where data cleaning is performed as proposed in the data cleaning protocol of SelfClean.

Best
Fabian

**Comment by divyashan** [comment]
Hi Fabian, thanks for your reply!! That makes sense - thanks again for all this work!

**Comment by FabianGroeger96** [comment]
I'm closing this issue and we'll stay in contact for the updated Fitzpatrick17k list.
